# alertmanager/alertmanager.yml
global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'app-password'

route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'receiver-email@gmail.com'
