# alertmanager/alertmanager.yml
global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'targetspotter11@gmail.com'
  smtp_auth_username: 'targetspotter11@gmail.com'
  smtp_auth_password: 'ktmu sziv mdly ayuw'

route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'targetspotter11@gmail.com'
